# Generated by Django 3.1.3 on 2023-02-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230226_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam',
            field=models.BooleanField(default=False),
        ),
    ]
